### ISSUE TITLE
Part numbers for non mechanically placed parts, version V1C

### ISSUE THREAD

**Issue by DOSputin** [damienmaguire/Prius-Gen3-Inverter#1]
A BOM is included for  V1C that lists the SMT parts that are placed from the JLCPCB library.  Parts numbers, designators and descriptions for the hand placed parts are missing from this BOM.  Please include these part numbers in a separate BOM file to help others in sourcing parts for assembly of boards.

**Comment by damienmaguire** [comment]
https://github.com/damienmaguire/Prius-Gen3-Inverter/blob/master/V1c/PriusGen3HandPlacedParts.csv

**Comment by damienmaguire** [comment]
Closed. Hand placed bom now on repo.
