### ISSUE TITLE
SGM3204 Discontinued

### ISSUE THREAD

**Issue by SRFirefox** [damienmaguire/Prius-Gen3-Inverter#3]
The SGM3204 part is unavailable from JLC and a check with LCSC indicates it is no longer in production. Depending on output current requirements, the OnSemi MAX1720 might make a drop-in replacement. If more current is required, the TI LM2776 is rated to 200mA, but has a different pinout than the original IC.

**Comment by damienmaguire** [comment]
Updated designs. Thanks for the heads up.

**Comment by damienmaguire** [comment]
Updated in Block 4 release to MAX735
